### ISSUE TITLE
Any plans for MPNS support?

### ISSUE THREAD

**Issue by lazaronixon** [calonso/ruby-push-notifications#1]
Dou you have plans for MPNS (Windows Phone)?
https://github.com/lazaronixon/pushmeup/blob/master/lib/pushmeup/mpns/core.rb

**Comment by calonso** [comment]
That looks good!! Would you like to collaborate and open a pull request to integrate it? That would be awesome!!

**Comment by lazaronixon** [comment]
#3 Ok. I ported my implementation from PushmeUP to ruby-push-notifications. But I didn't had opportunity to test it on device yet maybe this week i will do this.

**Comment by calonso** [comment]
MPNS Support added here: https://github.com/calonso/ruby-push-notifications/commit/787806bd79cc7d82841341e6ebbf0a757993956b
