### ISSUE TITLE
Change Android example

### ISSUE THREAD

**Issue by timbaas** [calonso/ruby-push-notifications#11]
In the GCM example the notification is created with:

`{ text: "Hello GCM world" } `

But it should be:

`{ message: "Hello GCM world" } `

**Comment by calonso** [comment]
Hi @timbaas thanks for your message!!

Could you please elaborate a little bit more? According to the docs it doesn't seem to matter, actually it all would depend on the client implementation (fields the client is expecting)

https://developers.google.com/cloud-messaging/http-server-ref#notification-payload-support

Regards

**Comment by timbaas** [comment]
Hi @calonso,

I'm using Cordova with https://github.com/phonegap/phonegap-plugin-push .
Because I didn't do any setup and am more familiar with APN (which uses a standard format) I thought 'message' was a default body for Android messages, but seems I'm not right about that, my bad..!

I'll read through the link, thanks!

**Comment by calonso** [comment]
Cool, leet me know if you need any more help!

**Comment by timbaas** [comment]
@calonso, according to the docs, next to 'registration_ids' we can send a 'data' and 'notification' attributes. I see in the source we can only send 'data' at the moment but no 'notification' attribute, right? I think it would be nice if the `GCMNotification.as_gcm_json` method would take the `@data` object and add the `registration_ids` to it, instead of creating a new object and putting `@data` in `data`.

Creating a notification would look like this: 
`RubyPushNotifications::GCM::GCMNotification.new ["..."], { data: { score: 10 }, notification: { title: "Score updated!" } }`

It could be backwards compatible if it only does this when both `notification` and `data` are present in the `@data` object.

What do you think?

**Comment by calonso** [comment]
Sending both `notification`and `data` payloads will make the phone receive the `notification` payload when received and then the `data` one when in foreground. Is that what you exactly need?

If this is what you need I'm happy for you to collaborate with this gem and make the changes and I'll help reviewing and providing feedback.

Committers are always welcome here!

**Comment by avdept** [comment]
Faced same issue, while trying to push notification to android 5.1.1. Had to use `message` key instead of `body`. Also was missing `id`, so added as `id: Time.now.to_i`
