### ISSUE TITLE
require "Forwardable"

### ISSUE THREAD

**Issue by Faz95210** [calonso/ruby-push-notifications#14]
Hi, I've recently downloaded this gem, and I had an issue where I had to go inside the gem and add a 《`require "Forwardable"`》or the gem would prevent my program from working. 

<h6>I'm using ruby 2.3.</h6>

**Comment by calonso** [comment]
That's weird. I've tested and in Ruby 2.3 you can use both low and upcase.
```
2.3.3 :001 > require 'Forwardable'
 => true

2.3.3 :001 > require 'forwardable'
 => true
```

Which was your error and where exactly you added that `require`?

**Comment by Faz95210** [comment]
I don't recall, it happened this week-end, I'll tell you that this Thursday it is on my school's raspberry.

**Comment by calonso** [comment]
Ok, cool. In the meantime I'll increase the CI Ruby's versions to cover until 2.3 just in case

**Comment by Faz95210** [comment]
I couldn't use our raspberry today so I had to reproduce the bug on my macbook. After installing the gem and running this :
```
require 'ruby-push-notifications'
puts "foo"
```
 I get this error :
```
 /Library/Ruby/Gems/2.0.0/gems/ruby-push-notifications-1.0.0/lib/ruby-push-notifications/notification_results_manager.rb:6:in `<module:NotificationResultsManager>': uninitialized constant RubyPushNotifications::NotificationResultsManager::Forwardable (NameError)
```
After adding require 'Forwardable' to notification_results_manager.rb everything works fine.
My macbook is running ruby 2.0.0p648
