### ISSUE TITLE
Support WNS for UWP (Windows 10) apps

### ISSUE THREAD

**Issue by Shayon** [calonso/ruby-push-notifications#19]
Can we add support for [Windows Push Notification Services (WNS)](https://docs.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-windows-push-notification-services--wns--overview)? This will support pushing to Universal Windows Platform apps.

**Comment by calonso** [comment]
Is it different from [MPNS](https://github.com/calonso/ruby-push-notifications/blob/master/examples/mpns.rb)? If it is, of course we can add that feature. PRs are always welcome and I'll help you as much as I can if you need help to do it.

**Comment by Shayon** [comment]
Yep, different from MPNS.  And, awesome thanks for the offer for help!

**Comment by krim** [comment]
@Shayon, @calonso I'm added WNS support in this PR: https://github.com/calonso/ruby-push-notifications/pull/21

**Comment by calonso** [comment]
Amazing @krim, thank you very much!! I'll review it ASAP. 

Thanks again for your work!!

**Comment by calonso** [comment]
Closing this as #21 was merged adding it
