### ISSUE TITLE
Firebase Cloud Messaging support

### ISSUE THREAD

**Issue by runa** [calonso/ruby-push-notifications#20]
Hi! I was wondering if you are planning to support Firebase Cloud Messaging pushes!

https://firebase.google.com/docs/cloud-messaging/

Thanks!

**Comment by calonso** [comment]
Hi, I'm glad to add as much features as possible, but currently I don't have any time/project to specifically develop the FCM feature. PRs are always welcome and I'm happy to help you as much as I can to get that feature added if you decide to go ahead and contribute with it.

Thanks!

**Comment by StevenWoo** [comment]
If one uses firebase on android supposedly one can get the GCM token with
   String firebase_token = FirebaseInstanceId.getInstance().getToken();
but this does not work with the GCM example  - it succeeds but your device does not get a notification.

**Comment by calonso** [comment]
That sounds weird... unfortunately currently I have no time nor resources to investigate it deeper. Could you @StevenWoo please debug it? It would be lovely to support that into the gem.
Thanks!

**Comment by calonso** [comment]
Closing as stale... Please reopen it if required or add your outcome if you found a solution should it be helpful for anyone else...
Thanks!

**Comment by DrissTM** [comment]
Hi !

Google recently announced that [GCM is now deprecated and will be completely removed on April the 11th 2019](https://developers.google.com/cloud-messaging/android/android-migrate-fcm).

Is there any plan on updating the gem before this happen ?

Thanks !

**Comment by calonso** [comment]
It would be great to have it updated, but TBH, I don't have any spare time to put into it so I cannot commit to it. It would be lovely if someone else volunteers...
