### ISSUE TITLE
FCM (Not released on rubygems yet)

### ISSUE THREAD

**Issue by Juksefantomet** [calonso/ruby-push-notifications#24]
FCM has been implemented **but not released** with current version on Rubygems.

For those features and testing use the below steps:

Remove current version installed from rubygems and manually build:
  1. gem uninstall ruby-push-notifications
  2. git clone this_repo
  3. cd ruby-push-notifications
  4. gem build ruby-push-notifications.gemspec
  5. gem install ruby-push-notifications-x.x.x

you now have current branch version installed with the FCM implementation active.

**Comment by calonso** [comment]
Thanks for this information @Juksefantomet 
I've just [bumped the gem version to 1.3.0](https://github.com/calonso/ruby-push-notifications/commit/3662e11ef88c3f4df71e5a3aafed034b6df44d5b) and [published it to Rubygems](https://rubygems.org/gems/ruby-push-notifications/versions/1.3.0). Also tried installing it and worked so it should be fine. Can you please double check as well?

**Comment by Juksefantomet** [comment]
@calonso i can confirm the new version is working as intended and test push has successfully arrived at mobile unit. We are good to go! :smile:

**Comment by calonso** [comment]
Amazing, thanks for your help! Next time we have to remember to bump the version at the gemspec file as part of the PR. Have a nice day

**Comment by Juksefantomet** [comment]
Absolutely! Thank you and the same!
