### ISSUE TITLE
Password for pem file

### ISSUE THREAD

**Issue by waqar-baig** [calonso/ruby-push-notifications#5]
I have a password protected pem file for IOS.
How do I set the password for the pem file?
Please help.

**Comment by calonso** [comment]
Can you try adding the password as the second argument to `OpenSSL::PKey::RSA.new cert` call here? https://github.com/calonso/ruby-push-notifications/blob/master/lib/ruby-push-notifications/apns/apns_connection.rb#L32

**Comment by waqar-baig** [comment]
Ok, I'll create a pull request for the same.

**Comment by waqar-baig** [comment]
Here's the pr for the same #6
